[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java"

    [[platform.libraries]]
    artafactId = "commons-lang3"
    version = "3.8.1"
    path = "./lib/commons-lang3-3.8.1.jar"
    groupId = "org.apache.commons"
    modules = ["auth"]

    [[platform.libraries]]
    artafactId = "commons-logging"
    version = "1.1.1"
    path = "./lib/commons-logging-1.1.1.jar"
    groupId = "commons-logging"
    modules = ["auth"]

    [[platform.libraries]]
    artafactId = "slf4j-api"
    version = "1.7.26"
    path = "./lib/slf4j-api-1.7.26.jar"
    groupId = "org.slf4j"
    modules = ["auth"]
